apiVersion: v1 
kind: Pod 
metadata:
  name: eventstreamcoreapi-production
  labels:
    component: web2
    environment: production
    app: stormweb
spec:
  containers:
    - name: stormapiproduction
      imagePullPolicy: Always
      image: devbolddocker.azurecr.io/eventstreamcoreapi:67
      command: ["dotnet",  "BOLD.CoreEventsStreamService.Api.dll", "--environment=QA"]
      ports:
        - containerPort: 80
  imagePullSecrets:
  - name: myregistrykey
