apiVersion: v1
kind: Pod
metadata:
  name: eventstreamcoreapi-pod
  labels:
    component: web
spec:
  containers:
    - name: eventstreamcoreapi
      imagePullPolicy: Always
      image: devbolddocker.azurecr.io/eventstreamcoreapi:68
      ports:
        - containerPort: 80
  imagePullSecrets:
  - name: myregistrykey
